[package]
name = "fairy-ring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix-sdk = { version = "0.6.2", features = ["appservice"] }
tokio = "1.28.2"
